beyla:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 1Gi
  env:
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "<oodle_otel_endpoint>"
    OTEL_EXPORTER_OTLP_HEADERS: "X-API-KEY=<oodle_api_key>"
    BEYLA_KUBE_CLUSTER_NAME: "cluster"

    BEYLA_NAME_RESOLVER_SOURCES: "k8s,dns"
